version: '2'
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
        - "2181:2181"
  kafka:
    image: confluent/kafka:0.10.0.0-cp1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME={Docker Machine IP} #192.168.99.101
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
